// <auto-generated />
using GerenciamentoDeContatosWeduka;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoDeContatosWeduka.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GerenciamentoDeContatosWeduka.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonId = 1,
                            Type = "Phone",
                            Value = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            PersonId = 1,
                            Type = "Email",
                            Value = "john.doe@example.com"
                        },
                        new
                        {
                            Id = 3,
                            PersonId = 2,
                            Type = "Phone",
                            Value = "234-567-8901"
                        },
                        new
                        {
                            Id = 4,
                            PersonId = 2,
                            Type = "Email",
                            Value = "jane.smith@example.com"
                        },
                        new
                        {
                            Id = 5,
                            PersonId = 3,
                            Type = "Phone",
                            Value = "345-678-9012"
                        },
                        new
                        {
                            Id = 6,
                            PersonId = 3,
                            Type = "Email",
                            Value = "alice.johnson@example.com"
                        },
                        new
                        {
                            Id = 7,
                            PersonId = 4,
                            Type = "Phone",
                            Value = "456-789-0123"
                        },
                        new
                        {
                            Id = 8,
                            PersonId = 4,
                            Type = "Email",
                            Value = "bob.brown@example.com"
                        },
                        new
                        {
                            Id = 9,
                            PersonId = 5,
                            Type = "Phone",
                            Value = "567-890-1234"
                        },
                        new
                        {
                            Id = 10,
                            PersonId = 5,
                            Type = "Email",
                            Value = "carol.white@example.com"
                        });
                });

            modelBuilder.Entity("GerenciamentoDeContatosWeduka.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Carol White"
                        });
                });

            modelBuilder.Entity("GerenciamentoDeContatosWeduka.Models.Contact", b =>
                {
                    b.HasOne("GerenciamentoDeContatosWeduka.Models.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GerenciamentoDeContatosWeduka.Models.Person", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
